version: '3.8'

services:
  build:
    image: golang:1.22-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o ./bin/nixos_builds_manager main.go"